# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cdac4d15c1dbaeae75ff7b8ffdd262fef1f574992dbe644010a7c962d5faea0803b7f6a0bff22f18a783de536dceaa29bb3b263e884492fce380c5836773893

test:
  secret_key_base: 845dff8bacf47e370bc93497a4db9a379b49a86c535498f2cb2d23b8f840b08fd31db734a47e0b94adbc16091fa5c186b1692a45820e568e4fcd52255600b9c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
